[project]
name = "audio-detector"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "numpy>=2.5.2",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "torch>=2.13.0",
    "transformers>=5.16.1",
    "uvicorn>=0.52.4",
]
